# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v0.1.0
_src_path: https://github.com/flaudisio/copier-common-files.git
repo_author_name: Flaudísio Tolentino
repo_description: Helper scripts for miscellaneous purposes.
repo_name: Scripts
