---
extends: default

rules:
  braces:
    max-spaces-inside: 1
    level: error
  brackets:
    max-spaces-inside: 1
    level: error
  comments-indentation: disable
  document-start:
    ignore: |
      **/.copier-answers*.yml
  empty-lines:
    max: 1
  indentation:
    spaces: 2
  line-length:
    max: 120
